services:
  - type: web
    name: ytproxy
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT --timeout 120 server:app
    envVars:
      - key: PORT
        value: 3007
      - key: PYTHON_VERSION
        value: 3.11.0
